### ISSUE TITLE
curl超时怎么解决

### ISSUE THREAD

**Issue by janpun** [overtrue/laravel-filesystem-cos#17]
上传大文件时出现curl超时，貌似是60秒，但我研究了半天没找到设置的地方，麻烦告知下，谢谢
`production.ERROR: cURL error 28: Operation timed out after 60000 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) `

**Comment by overtrue** [comment]
https://github.com/overtrue/laravel-filesystem-cos?tab=readme-ov-file#configuration 配置里有写

**Comment by janpun** [comment]
看到了，感谢
