### ISSUE TITLE
Laravel8  guzzlehttp/guzzle 需要7.2.0

### ISSUE THREAD

**Issue by 8108905** [overtrue/laravel-filesystem-cos#3]
Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - freyo/flysystem-qcloud-cos-v5 2.0.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.0.1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.0.2 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.0.3 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install freyo/flysystem-qcloud-cos-v5 2.1.1|install guzzlehttp/guzzle 6.5.x-dev
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for freyo/flysystem-qcloud-cos-v5 ^2.0 -> satisfiable by freyo/flysystem-qcloud-cos-v5[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1].

希望修复下 谢谢

**Comment by overtrue** [comment]
您是不是提错地方了？https://github.com/freyo/flysystem-qcloud-cos-v5
