### ISSUE TITLE
laravel 8报错

### ISSUE THREAD

**Issue by anerg2046** [overtrue/laravel-filesystem-cos#5]
#message: "Method Overtrue\CosClient\Exceptions\ClientException::report() does not exist"
  #code: 0
  #file: "/Users/coeus/Data/www/mini-pd-server/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php"
  #line: 147

**Comment by overtrue** [comment]
新坑已填：https://www.php.net/manual/en/function.is-callable.php#118623
